[package]
name = "git-point"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["wrap_help"] }
env_logger = "0.11.3"
log = { version = "0.4.21", features = ["std"] }
